function doAll() {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            getBookmarks(user);
            getCategories(user);
        } else {
            console.log("No user is signed in");
        }
    });
}
doAll();


// Store category into local storage so user can navigate back to desired message board
function storeCategory(value) {
    let key = "currentCategory";
    localStorage.setItem(key, value);
};


// Store category title into local storage for the desired message board
function storeCategoryTitle(value) {
    let key = "currentCategoryTitle";
    localStorage.setItem(key, value);
};


// Populate my profile page with bookmarked posts
const myBookmarks = document.getElementById("my-bookmarks")
function getBookmarks(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {

            // Get the Object of bookmarks
            var bookmarks = userDoc.data().bookmarks;
            console.log(bookmarks);
						
			// Get pointer the new card template
            let newcardTemplate = document.getElementById("bookmarkCardTemplate");

			// Iterate through the bookmarked posts object
            Object.keys(bookmarks).forEach(postKey => {
                console.log(postKey);
                var postCategory = bookmarks[postKey].category;
                console.log(postCategory)
                db.collection("categories").doc(postCategory).collection("posts").doc(postKey).get().then(doc => {
                    var title = doc.data().title; // get value of the "name" key
                    var docID = doc.id;  //this is the autogenerated ID of the document
                    var image = doc.data().image;
                    
                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);

                    //update title and some pertinant information
                    newcard.querySelector('.card-title').innerHTML = title;
                    newcard.querySelector('.card-image').src = image; //Example: NV01.jpg
                    // Allow user to navigate to bookmarked post
                    newcard.querySelector('a').addEventListener("click", () => {
                        storeCategory(postCategory);
                    });
                    newcard.querySelector('a').href = "view_message.html?postID=" + docID;
                    myBookmarks.appendChild(newcard);
                })
            });
        })
}


// Populate my profile page with bookmarked categories
const myCategories = document.getElementById("my-categories")
function getCategories(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {

            // Get the array of bookmarks
            var userCategories = userDoc.data().mycategories;
            console.log("user categories", userCategories);
						
			// Get pointer the new card template
            let newcardTemplate = document.getElementById("categoryCardTemplate");

			// Iterate through the bookmarked posts object
            userCategories.forEach(categoryID => {
                console.log(categoryID);

                db.collection("categories").doc(categoryID).get().then(doc => {
                    var title = doc.data().title; // get value of the "name" key
                    var docID = doc.id;  //this is the autogenerated ID of the document
                    var image = doc.data().image;
                    
                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);

                    //update title and some pertinant information
                    newcard.querySelector('.card-title').innerHTML = title;
                    newcard.querySelector('.card-image').src = image; //Example: NV01.jpg
                    // Allow user to navigate to bookmarked post
                    newcard.querySelector('a').addEventListener("click", () => {
                        storeCategory(docID);
                        storeCategoryTitle(title)
                    });
                    newcard.querySelector('a').href = "message_board.html";
                    myCategories.appendChild(newcard);
                })
            });
        })
}
